development:
  adapter: mysql2
  encoding: utf8
  pool: 100
  timeout: 5000
  database: sns_dev
  username: root
  password: 
  reconnect: true
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  pool: 100
  timeout: 5000
  database: sns_test
  username: root
  password: 
  reconnect: true
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  pool: 100
  timeout: 5000
  database: sns
  username: root
  password: 
  reconnect: true
  host: localhost
  socket: /tmp/mysql.sock


#development:
#  adapter: mysql2
#  encoding: utf8
#  pool: 100
#  timeout: 5000
#  database: tellme
#  username: darammg
#  password: eoqkr2014
#  reconnect: true
#  host: dev8.darammg.com

#development:
#  adapter: mysql2
#  encoding: utf8mb4
#  charset: utf8mb4
#  collation: utf8mb4_general_ci
#  username: root
#  password: 
#  host: localhost
#  timeout: 5000
#  database: tellme_utf8mb4
